import { Game, PlatformFeature } from '@/types/game';
export const GAMES: Game[] = [
  {
    id: 'rock-toss',
    name: 'Rock Toss',
    description: 'Throw rocks into the mystical pond and watch the ripples of fortune! Each toss is pure luck - will you hit the golden jackpot zone?',
    shortDescription: 'Luck-based rock throwing jackpot',
    icon: '🪨',
    color: '#8B4513',
    gradient: 'from-amber-600 to-orange-700',
    features: ['Pure Luck', 'Jackpot Zones', 'Random Rewards', 'Instant Payouts'],
    difficulty: 'Easy',
    popularity: 95,
    isFeatured: true,
  },
  {
    id: 'water-drop',
    name: 'Water Drop',
    description: 'Catch falling water droplets in your magical vessel! Each drop brings different rewards - from silver coins to diamond treasures!',
    shortDescription: 'Water droplet collection game',
    icon: '💧',
    color: '#1E90FF',
    gradient: 'from-blue-400 to-cyan-500',
    features: ['Drop Collection', 'Treasure Rewards', 'Random Bonuses', 'Crystal Prizes'],
    difficulty: 'Easy',
    popularity: 88,
    isNew: true,
  },
  {
    id: 'wheel-spin',
    name: 'Wheel of Fortune',
    description: 'Spin the mystical wheel of fortune and watch it land on amazing rewards! Pure luck determines your fate - will you hit the jackpot?',
    shortDescription: 'Luck-based wheel spinning jackpot game',
    icon: '🎡',
    color: '#DC2626',
    gradient: 'from-red-500 to-pink-600',
    features: ['Pure Luck', 'Wheel Physics', 'Jackpot Zones', 'Instant Rewards'],
    difficulty: 'Easy',
    popularity: 95,
    isFeatured: true,
  },
  {
    id: 'swifte',
    name: 'Swifte',
    description: 'Click lightning-fast targets to rack up points before the timer runs out.',
    shortDescription: 'Fast reflex target clicker',
    icon: '⚡',
    color: '#F59E0B',
    gradient: 'from-orange-500 to-red-500',
    features: ['Reflex Challenge', 'Combo Scoring', 'Dynamic Spawns', 'Speed Bonus'],
    difficulty: 'Medium',
    popularity: 82,
    isNew: true,
  },
  {
    id: 'monimak',
    name: 'Monimak',
    description: 'Flip cards to find matching mystical symbols before time runs out.',
    shortDescription: 'Memory match puzzle',
    icon: '🔮',
    color: '#8B5CF6',
    gradient: 'from-purple-500 to-indigo-500',
    features: ['Memory Pairs', 'Time Attack', 'Combo Bonuses', 'Clean UX'],
    difficulty: 'Medium',
    popularity: 76,
  },
  {
    id: 'gadmod',
    name: 'Gadmod',
    description: 'Merge tiles to build higher values and chase your best score.',
    shortDescription: '2048-style tile merger',
    icon: '🎯',
    color: '#10B981',
    gradient: 'from-emerald-500 to-teal-500',
    features: ['Tile Merging', 'Level Ups', 'Keyboard Controls', 'Smooth Animations'],
    difficulty: 'Medium',
    popularity: 84,
    isFeatured: true,
  },
];

export const PLATFORM_FEATURES: PlatformFeature[] = [
  {
    id: 'instant-play',
    title: 'Instant Play',
    description: 'Jump into any game instantly without downloads or installations',
    icon: '🚀',
    color: '#3B82F6',
  },
  {
    id: 'fair-play',
    title: 'Fair Play',
    description: 'Provably fair algorithms ensure every game is completely random',
    icon: '⚖️',
    color: '#10B981',
  },
  {
    id: 'rewards',
    title: 'Amazing Rewards',
    description: 'Win incredible prizes and climb the global leaderboards',
    icon: '🏆',
    color: '#F59E0B',
  },
  {
    id: 'community',
    title: 'Vibrant Community',
    description: 'Connect with players worldwide and share your achievements',
    icon: '👥',
    color: '#8B5CF6',
  },
];

export const SITE_CONFIG = {
  name: 'Mariska Smit',
  tagline: 'Where Luck Meets Skill',
  description: 'Experience the ultimate luck-based gaming platform with thrilling games, fair play, and amazing rewards.',
  url: 'https://mariska.com',
  social: {
    twitter: '@mariska_games',
    discord: 'mariska-community',
    telegram: 'mariska_official',
  },
} as const;
